### ISSUE TITLE
Limited number of tweets

### ISSUE THREAD

**Issue by stormstricker** [NandanDesai/TwitterScraper4J#1]
Hello! You are saying, that a number of tweets it can retrieve for a given user is limited to around 3200 ? What is the reason behind this? Also, it looks like you are using `JSoup`, maybe getting all of the tweet history could be accomplished with `Selenium`?

**Comment by NandanDesai** [comment]
> You are saying, that a number of tweets it can retrieve for a given user is limited to around 3200 ? What is the reason behind this?

Yes, the number of tweets you can retrieve for a given user is around 3200. Sometimes you can get up to 4000 tweets. I know that the Twitter API's rate limit is around 3200 for a user. But while scraping Twitter page too, the number of tweets you can fetch is around that number although it varies in a few cases. I don't know the exact reason why this happens. 

> it looks like you are using JSoup

Twitter, as other modern websites, is heavily JavaScript dependent. It dynamically loads tweets as you scroll the page. And building a web scraper for that kind of scenario is very difficult. Also, if Twitter changes the layout of it's website, then the scraper breaks. So, the way I solved this problem is that I am hitting Twitter's legacy page which returns data in plain HTML which doesn't contain any JavaScript (You can try this yourself. Just disable the JavaScript in your browser and visit Twitter. You'll be taken to it's legacy page). So, it becomes easier to scrape and as this legacy page is meant to remain intact (i.e., the layout/theme of the page won't be changed), the scraper will be pretty much stable. And also the library becomes very lightweight as Jsoup is just an HTML parser essentially. 

> maybe getting all of the tweet history could be accomplished with Selenium?

You could try to use Selenium to scrape the Twitter's main site and try to simulate scrolling event to load more tweets, but I think it will stop at around 3200 tweets as well (although I've never tried it so I'm not sure).

There is a popular Python project called [twint](https://github.com/twintproject/twint) which claims to be able to fetch ALL the tweets for a given user. I'm not sure how they are managing to do it but it's an Open Source project and you can go through their code if you are interested.

**Comment by stormstricker** [comment]
Thanks for reply. I checked out twint turned out it breaks when one tries to get tweets from a big account (the one that had like 400k tweets). Twint ends up breaking ratelimits or something, even though it can get the 3k tweets from the less big accounts.

And you were right about 3200 - twint doesn't seem to get more than that number either. There are some paid services that offer that, but they store all tweets as they go in their own db.

That gets me thinking - in readme it says TwitterScraper4J has no ratelimits. Is that a good thing? Having recently made a Twitter bot that sent requests periodically, it's absolutely necessary to introduce rate limits to prevent being blocked imo.

**Comment by NandanDesai** [comment]
Yes. You're right. If you send too many requests, Twitter may block your IP. That's why, in cases where a large amount of data is being fetched from Twitter, Thread.sleep() should be added to have some delay. You can see me doing this in README code examples already. 


_TwitterScraper twitterScraper = TwitterScraper.getInstance();
Iterator<List<Tweet>> it=twitterScraper.getAllTweets("realDonaldTrump");
while(it.hasNext()){
    List<Tweet> tweets=it.next();
    for(Tweet tweet:tweets){
        System.out.println(tweet);
    }
    Thread.sleep(1000);
}_

A sleep of 1 second is enough. Else if you send bulk requests, Twitter will reply with "Too many requests" error. And eventually maybe ban you. I could have included this sleep functionality within the library but I wanted to give user more flexibility to choose the amount of delay they want according to their performance requirements. 


I hope this was what you were asking for and I hope I answered your question.
