### ISSUE TITLE
Proxies support

### ISSUE THREAD

**Issue by stormstricker** [NandanDesai/TwitterScraper4J#2]
I had to use your library for a new project of mine and I used `TwitterScraper`'s `getUserTimeline` method that seems to return 2 - 30 most recent tweets. I looked into the code and found that you send a POST request to a `https://mobile.twitter.com/i/nojs_router?path=/` + username endpoint using Jsoup. Very smart! Especially that setting of the `Referer` header. 

I wanted to hit that page as often as possible - you said in another issue that 1 second of sleep inbetween requests is enough (is it - for this method?) - but I got worried and decided to try to use several proxy servers to spread out the requests to decrease the frequency per IP address. So I've got good code that can get around 500 proxies out of which around 15 are valid (as in they can send and return GET requests to https://twitter.com successfully). 

So I've set up something of a proxy rotation, but when I tried to use it with the `getUserTimeline` method, I found that proxies return 405 method not allowed error which seems to happen because nginx servers don't allow for POST requests to return static html content. Which is a big shame. Perhaps you know a way around it, given your extensive knowledge about html requests and headers and stuff? And if you think it would be useful, I could make a push request with my proxies code so that it could be included in the library.

Or maybe there is some other way to achieve what I'm trying to do (getting new tweets, to, say, print them into a file right as they come)? I can see there are classes like `TweetStream`, but am unsure if it should be used for that.

Sorry for a longpost, overall this library is awesome, and is of great help!

**Comment by NandanDesai** [comment]
Hi! I'm glad this library was helpful to you.

I actually have plans for adding proxy support for this library in future. 

If you want to get new tweets from a particular user as and when they occur, then you need to call  `getUserTimeline` method every few seconds and then check for new tweets in the `List` that you got. You say you are using 1 second delay. That's fine. But since you will be calling that method indefinitely, it is safe to use a random delay to simulate human action on that page. For example, you can use something like `Thread.sleep(rand(1000,5000))` where `rand(x,y)` returns a random number between x and y. You can write the logic for `rand()` method on your own. But still you do need to use a proxy because we don't know how effective Twitter's bot detection systems are. 

Regarding the 405 error that you are getting for using proxy, you need to send me the stack trace or a code snippet or something that would help me better understand your situation there. If you send an HTTP GET request to `https://mobile.twitter.com/i/nojs_router?path=/`, then Twitter replies with 405 because only POST is allowed to hit that URL. I had heard somewhere that some proxy servers change POST to GET request (like a question posted [here](https://www.digitalocean.com/community/questions/post-request-redirects-to-get-in-nginx-proxy-and-nodejs)). So it shouldn't happen that your proxy server is changing POST methods to GET and then sending that to Twitter and Twitter is replying with 405.

I don't recommend you to use `TweetStream`. That class is still experimental and needs some work to be done on it. 

> I could make a push request with my proxies code so that it could be included in the library.

This project is part of another bigger project of mine. Although this library works fine as it is, I still have a few more features to add into it. So, I'm currently not accepting any pull requests. Sorry about that. You can let me know the changes you have made to this library to suit your requirements. I would love to see that!

**Comment by stormstricker** [comment]
Hello! Thank you for replying! 

Yes, I know _Twitter_ would send 405 if I send GET instead of POST to that endpoint.
However, from what I've researched a server nginx would also send a 405 if you try to send it a POST request that accesses a static resource: https://stackoverflow.com/questions/51613180/nginx-post-method-does-not-work. And since you can't make changes to have those proxy servers are considered, and they wouldn't server that request, there doesn't seem to be a way to use proxies (at least those open free proxies that you don't own yourself).

Thank you for the `rand` idea, I'm gonna use it! However, can't use any proxies for the reasons described above...

The changes I've made were basically to the methods that go down from `getUserTimeline` method, 

TwitterScraper:
```
public List<Tweet> getUserTimeline(String username) throws IOException, TwitterException {
        return getUserTimeline(username, null);
    }

    public List<Tweet> getUserTimeline(String username, Proxy proxy) throws IOException, TwitterException {
        if (username == null || username.equals("")) {
            throw new IllegalArgumentException("\"username\" cannot be null or empty");
        }
        TweetScraper tweetScraper=new TweetScraper(cookies);
        return tweetScraper.getHomeTimeline(username, proxy);
    }
```
TweetScraper:
```
List<Tweet> getHomeTimeline(String username) throws IOException, TwitterException {
        return getHomeTimeline(username, null);
    }

        List<Tweet> getHomeTimeline(String username, Proxy proxy) throws IOException, TwitterException {
```

Utils:

```
static Document getDocument(String url, Map cookies, Class callingClass) throws IOException, TwitterException {
        return getDocument(url, cookies, callingClass, null);
    }

    static Document getDocument(String url, Map cookies, Class callingClass, Proxy proxy) throws IOException, TwitterException {
        Connection.Response response;
```

**Comment by NandanDesai** [comment]
Cool! I will be adding proxy support to this library soon. I personally use Tor proxy for any scraping related tasks. You can try to use that if you want.

**Comment by NandanDesai** [comment]
I have added proxy support to this library. If you want to use a Tor proxy (as I suggested in the above thread), then the simplest way would be to install Tor Browser in your system and keep the Tor Browser running so that it hosts a SOCKS proxy server on your localhost at port 9150. Then you can build an instance of `TwitterScraper` class like this:
```
Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 9150));
TwitterScraper twitterScraper = TwitterScraper.builder().proxy(proxy).build();
```
Now you can use that `twitterScraper` and call the methods you want! If you are using this library as a JAR file then don't forget to download the new updated JAR file from the release section. I would love to hear your feedback on this!

**Comment by stormstricker** [comment]
Thank you so much for updating the library and the TOR advice! This approach would route all program traffic via a Tor Browser, right? But then the IP the Twitter sees would depend on how often TOR changes it's IP? I"ve made it check the ports 9150 and 9050 and if tor is working on either, route through them. But how can I be sure it changes the IP address and how often it does? Do you just trust the TOR Browser to do the rest?

**Comment by NandanDesai** [comment]
You can test if the IP address is really changed by Tor Browser proxy by using some other tools like curl or wget. But usually, if your program doesn't throw any proxy-related exceptions, then the proxy will be working fine. And according to [Tor FAQs](https://2019.www.torproject.org/docs/faq.html.en#ChangePaths) ("How often does Tor change its paths?"), Tor changes IP address every 10 mins. 

Use the below code with correct proxy IP address (127.0.0.1 in your case) and correct port number (9150) and if no exceptions are thrown, then Twitter will be seeing Tor's IP address and not yours.
```
Proxy proxy = new Proxy(Proxy.Type.SOCKS, new InetSocketAddress("127.0.0.1", 9150));
TwitterScraper twitterScraper = TwitterScraper.builder().proxy(proxy).build();
```

**Comment by stormstricker** [comment]
Alright, thanks again!
